[package]
name = "kyber"
description = "Code editor focused on transformations."
version = "0.1.0"
edition = "2018"
authors = ["Shelby Doolittle <shelby@shelbyd.com>"]
license = "MIT"

[dependencies]
termion = "1.5"
tui = "0.15"
